listen:
  http: ":80"
  https: ":443"

domains:
  - domain: picture-proof.com
    ssl:
      cert_file: /etc/letsencrypt/live/picture-proof.com/fullchain.pem
      key_file: /etc/letsencrypt/live/picture-proof.com/picture-proof.com-PrivateKey.pem
    redirect_to_https: true
    routes:
      - path: "/core/"
        proxy_pass: "http://localhost:8085"
      - path: "/storage/"
        proxy_pass: "http://localhost:9090"
      - path: "/"
        proxy_pass: "http://localhost:3000"
