#  // © 2023 Devinsidercode CORP. Licensed under the MIT License.
server:
  webroot: ./webroot
listen:
  http: ":80"
  https: ":443"

domains:
  - domain: picture-proof.com
    ssl:
      cert_file: /etc/letsencrypt/live/picture-proof.com/fullchain.pem
      key_file: /etc/letsencrypt/live/picture-proof.com/picture-proof.com-PrivateKey.pem
    redirect_to_https: true
    routes:
      - path: "/core/"
        proxy_pass: "http://localhost:8085"
      - path: "/storage/"
        proxy_pass: "http://localhost:9090"
      - path: "/"
        proxy_pass: "http://localhost:3000"
  - domain: manage.eyesync.app             # новый поддомен
    ssl:
      cert_file: /etc/letsencrypt/live/eyesync.app/fullchain.pem
      key_file: /etc/letsencrypt/live/eyesync.app/privkey.pem
    redirect_to_https: true
    routes:
      - path: "/"
        proxy_pass: "http://localhost:8787"
