server:
  port: 8080  # What port are we listening to?
  log_level: "info"  # Logging level (debug, info, warn, error)
  allowed_hosts:
    - "example.com"
    - "api.myserver.com"

proxy:
  routes:
    - path: "/api"
      backend: "http://backend1.local:8000"
      methods: ["GET", "POST"]
    - path: "/uploads"
      backend: "http://storage.local:9000"
      methods: ["POST"]

security:
  blocked_ips:
    - "192.168.1.100"
    - "10.0.0.50"
  blocked_user_agents:
    - "BadBot"
    - "Scrapy"
  enable_waf: true  # Enable Web Application Firewall
  ratelimit: 100  # Request limit (100 per minute)
