# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: sh

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: List assets (debug)
        run: |
          echo "Current path: $PWD"
          find . -name 'logo-full.png'

      - name: Build binary
        run: |
          go build -v -o deadendproxy-bin ./cmd

      - name: Run tests
        run: go test ./...

  build-bsd:
    name: Build on FreeBSD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: '13.2'
          mem: 2048
          prepare: |
            pkg install -y go git
          run: |
            sh ./scripts/deadendproxy-bsd.sh
            go version
            go build -buildvcs=false -v ./cmd/main.go -o deadendproxy-bsd
            go test ./...
